#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"
export RUNTIME_ROOT="${RUNTIME_ROOT:-${REPO_ROOT}/runs}"
export EXP_NAME="${EXP_NAME:-full_gradient_signed_grpo_probe_v1_seed42}"
export GRADIENT_PROBE_OUTPUT_DIR="${GRADIENT_PROBE_OUTPUT_DIR:-${RUNTIME_ROOT}/analysis/${EXP_NAME}}"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3}"
export PEFT_TYPE=full_gradient_probe
export LORA_RANK=0
export LORA_ALPHA=0
export LORA_DROPOUT=0.0
export LORA_FREEZE_A=False
export TARGET_MODULES="${TARGET_MODULES:-all-linear}"
export FULL_GRADIENT_PROBE_RANK="${FULL_GRADIENT_PROBE_RANK:-32}"
export FULL_GRADIENT_PROBE_SKETCH_WIDTH="${FULL_GRADIENT_PROBE_SKETCH_WIDTH:-40}"
export FULL_GRADIENT_PROBE_SVD_DEVICE="${FULL_GRADIENT_PROBE_SVD_DEVICE:-auto}"
export FULL_GRADIENT_PROBE_DISCOVERY_PROMPTS="${FULL_GRADIENT_PROBE_DISCOVERY_PROMPTS:-16}"
export FULL_GRADIENT_PROBE_CALIBRATION_PROMPTS="${FULL_GRADIENT_PROBE_CALIBRATION_PROMPTS:-16}"
export FULL_GRADIENT_PROBE_AUDIT_PROMPTS="${FULL_GRADIENT_PROBE_AUDIT_PROMPTS:-8}"
export FULL_GRADIENT_PROBE_CLIP_FACTOR="${FULL_GRADIENT_PROBE_CLIP_FACTOR:-2.5}"
export FULL_GRADIENT_PROBE_CONFIDENCE_Z="${FULL_GRADIENT_PROBE_CONFIDENCE_Z:-1.0}"
export TRAIN_PROMPT_BSZ="${TRAIN_PROMPT_BSZ:-16}"
export TRAIN_PROMPT_MINI_BSZ="${TRAIN_PROMPT_MINI_BSZ:-16}"
export N_RESP_PER_PROMPT="${N_RESP_PER_PROMPT:-8}"
export TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS:-10}"
export SAVE_FREQ=0
export RESUME_MODE=disable
export DATA_SEED="${DATA_SEED:-42}"
export PPO_DATA_LOADER_SEED="${PPO_DATA_LOADER_SEED:-42}"
export ACTOR_SHUFFLE=False
export USE_ORIG_PARAMS=True
export CONDA_ENV_NAME="${CONDA_ENV_NAME:-peft-for-rl}"
export LOG_DIR="${LOG_DIR:-${RUNTIME_ROOT}/logs/verl}"
export LOG_FILE="${LOG_FILE:-${LOG_DIR}/${EXP_NAME}.log}"

mkdir -p "${LOG_DIR}"
cd "${REPO_ROOT}"
export PYTHONPATH="${REPO_ROOT}"
exec >>"${LOG_FILE}" 2>&1
exec conda run --no-capture-output -n "${CONDA_ENV_NAME}" \
    bash "${REPO_ROOT}/examples/verl_train/run_dapo_math_boxed_stable_lora_1p5b_4gpu_8k.sh"
